spring.application.name=Api

# ========== SUPABASE DATABASE (POSTGRESQL) ==========
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.bdxdkduzwygnchezmhzb
spring.datasource.password=S1pentasUnimus
spring.datasource.driver-class-name=org.postgresql.Driver

# ========== JPA ==========
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========== SERVER ==========
server.port=8080
server.address=0.0.0.0

# ========== API KEY ==========
sipentas.api-key=SIPENTAS-APP-FIXED-KEY

postgresql://postgres.bdxdkduzwygnchezmhzb:S1pentasUnimus@aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres